### ISSUE TITLE
Ringtones from Local Files

### ISSUE THREAD

**Issue by fennifith** [fennifith/Alarmio#10]
Yep.

**Comment by crutchcorn** [comment]
https://github.com/TheAndroidMaster/Alarmio/commit/c17b1b59a4439564115cd899410556876a87954f#diff-1b28a6cda786dc360d62fa52ccb4333aR52

Taken from a convo between @TheAndroidMaster and I:
> Okay so my app opens the gallery, the user picks a photo, the app gets the result and tries to load it into an imageview
Problem: the image is on the SD card, and the paths are formatted weirdly. Glide, an image loading library, doesn't like weirdly formatted paths. Thus, I need to do something.
The path output for this specific image is along the lines of `8475-1837:DCIM/Pictures/something.jpg`
From prior experience, I know that 8475-1837 is some sort of id referencing the sd card
I then open the file explorer, and find a mysterious directory `/storage/8475-1837` that contains the contents of the sd card
Thus, my solution in code: `path = "/storage/" + path.replaceFirst(":", "/");`

**Comment by TheAndroidMaster** [comment]
@crutchcorn uhh #11 is the issue about background images I was talking about in the convo, this one's a feature request for something completely different.

**Comment by crutchcorn** [comment]
I'll work on this one too I guess

**Comment by fennifith** [comment]
Closed - thanks for helping, @quipri!
