### ISSUE TITLE
Alarm doesn't work on Xiaomi devices.

### ISSUE THREAD

**Issue by ABHISHEK-AMRUTE** [fennifith/Alarmio#102]
## Problem Identified
The MIUI automatically deny two permissions namely "Display pop-up window while running in the background" and "Show on lock screen". Allowing it manually will solve this issue, but it would be good if the app does it automatically.  
Refer to this image  
![WhatsApp Image 2020-03-24 at 19 24 41](https://user-images.githubusercontent.com/41743655/77550172-c4adc280-6ed6-11ea-8f15-40f329a8bacd.jpeg)

## Device Info

- Brand: `Xiaomi`
- Model name: `Redmi 6A`
- Android version: `Android 9.`

## Steps to Reproduce

Just turn on alarm and press lock screen button.

**Comment by fennifith** [comment]
Unfortunately, none of these permissions can be automatically granted; they all need to be enabled by the user. The app can provide a walkthrough / onboarding UI to do so, though...

I think #85 is _vaguely related_ to this, but "show on lock screen" is a device-specific option...

Issue #37 involves implementing [doubledotlabs/doki](https://github.com/doubledotlabs/doki) though, which does address all of these settings; the page for your device can be found [here](https://dontkillmyapp.com/xiaomi).
