### ISSUE TITLE
1.0.5 on f-droid

### ISSUE THREAD

**Issue by raboof** [fennifith/Alarmio#110]
I was eager to update to Alarmio 1.0.5, but found it's not available on F-Droid yet.

The metadata is already updated at https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/me.jfenn.alarmio.yml

The latest build failed due to infrastructure issues though: https://f-droid.org/wiki/page/me.jfenn.alarmio/lastbuild . This should be automatically retried.

(there is no action required/possible on 'our' side at this point AFAICS, just wanted to share what I figured out so far ;) )

**Comment by fennifith** [comment]
Hm, it looks like it was retried successfully but hasn't updated on their website yet. I'm not sure what the update frequency is for that, though - it might just take a week or two to roll out.
