### ISSUE TITLE
[Feature request] Dismiss alarm on shake

### ISSUE THREAD

**Issue by kentone** [fennifith/Alarmio#127]
This was a feature from the LineageOS clock (I think) that I found quite cool, just take note of it if you guys think is cool too :)

Keep the good work 😋

**Comment by fennifith** [comment]
I think this is a duplicate of #12 lol

I'll probably work on custom alarm interfaces as a generic extensible thing for a future version, so all the "solve a puzzle to dismiss" / related feature requests will likely be addressed at once.
