### ISSUE TITLE
F-droid publication

### ISSUE THREAD

**Issue by lionirdeadman** [fennifith/Alarmio#24]
It'd be really to have this in F-droid!

I don't believe there's anything blocking this from being published there. ;)

**Comment by fennifith** [comment]
I'd like to limit its distribution a little bit until I fix major issues like #25 (which I have failed to document until now) that affect the core functionality. While there are downloads through my website and GitHub releases, I can at least assume that people using these either know what they are doing or that it is an alpha / pre-release (and the same with users on the Play Store).

**Comment by lionirdeadman** [comment]
Yeah, that's understandable.

Is there any proprietary libraries used though which would block its inclusion there?

**Comment by fennifith** [comment]
> Are there any proprietary libraries?

Nope. As of right now, all of the libraries are as follows:

- Android support / appcompat, Apache 2.0 (AOSP)
- [Material Components](https://github.com/material-components/material-components-android), Apache 2.0
- [afollestad/aesthetic](https://github.com/afollestad/aesthetic), Apache 2.0
- [jahirfiquitiva/FABsMenu](https://github.com/jahirfiquitiva/FABsMenu), Apache 2.0
- [mikereedell/sunrisesunsetlib-java](https://github.com/mikereedell/sunrisesunsetlib-java), Apache 2.0
- [google/ExoPlayer](https://github.com/google/ExoPlayer), Apache 2.0
- [bumptech/glide](https://github.com/bumptech/glide), BSD, part MIT, and Apache 2.0
- ...aaaand a couple written by me, mostly under Apache 2.0 ([AndroidUtils](https://github.com/fennifith/AndroidUtils) is MIT)

**Comment by lionirdeadman** [comment]
Nice. You seem to really like Apache ;)

I'll leave this issue open until it's published. (Whenever you think it is ready)

**Comment by IzzySoft** [comment]
"Subscribing" to this issue. For now, your app is [in my repo](https://apt.izzysoft.de/fdroid/index/apk/james.alarmio) (which is something between "testing" and "non-free" for F-Droid), so testers can already pick it from there. Please comment on this issue when you're ready for the official repo. As one of F-Droid's maintainers, I gladly help you filing the RFP (Request For Packaging) then 😃

**Comment by fennifith** [comment]
Thanks Izzy! I'll try to get it finished / cleaned up in the next couple days, sorry for the delay.

**Comment by fennifith** [comment]
First non-beta release is out! It should be ready now :)

**Comment by IzzySoft** [comment]
Thanks, @fennifith – and [here you go](https://gitlab.com/fdroid/rfp/issues/901) :smiley:
