### ISSUE TITLE
Implement "increasing volume"

### ISSUE THREAD

**Issue by fennifith** [fennifith/Alarmio#29]
This functionality is just missing. It's in the description for one of the settings. But it doesn't do anything. I forgot to write it. Rip.

**Comment by mjhram** [comment]
What about just setting the volume for specific level. The alarm is always in high volume and cannot be set.

**Comment by fennifith** [comment]
@mjhram You should be able to change the volume of the alarm channel, the same as the other volume channels on your phone. Maybe some skinned versions of Android have removed that functionality? Idk. Either way, #32 exists now.
