### ISSUE TITLE
a shortcut isn't available, standard Alarm ringtone bug.

### ISSUE THREAD

**Issue by machiav3lli** [fennifith/Alarmio#34]
have one wish and one bug to report:
1. the app doesn't open when I tap the hour in the notifications panel, even if it's the only app to provide an hour. so it would be great if you could integrate it more into the android UI(into this shortcut).

2. this one is the bug, steps:
- set a certain ringtone as standard
- create a new alarm
- still have to set a ringtone for this new alarm, otherwise it's "none"(this doesn't happen with a new timer)

thanks.

**Comment by fennifith** [comment]
1. What do you mean by "the hour in the notifications panel"? If it's a notification sent by Alarmio, clicking on it should always open Alarmio so that's probably a bug. If not, idk what you're asking for, you'll need to provide a more detailed explanation (sorry).
2. Yep, that's a bug.

**Comment by machiav3lli** [comment]
@fennifith I meant the clock in the left upper corner of the notifications panel. Cause the usual clock apps(deskclock, omni clock...) use it as a shortcut to the app, if you could implement it, that would be great. Thanks.
![](https://i.imgur.com/7sxj1WC.png)

**Comment by fennifith** [comment]
Okay I think I see what you mean, thanks. Creating a separate issue for this, as it's unrelated to the bug report.
