### ISSUE TITLE
Android Q Compatibility

### ISSUE THREAD

**Issue by fennifith** [fennifith/Alarmio#45]
Activities can no longer be launched while the app is in the background. I'm not sure how this affects `AlarmManager` (an activity launched directly by the system might be okay), but Alarmio will probably have to change its behavior of starting a BroadcastReceiver before checking the alarm and having that start the alarm activity. Rip.

**Comment by rien333** [comment]
No work around yet?

**Comment by fennifith** [comment]
Closing this as duplicate/invalid; #85 contains a better description of the issue.
