### ISSUE TITLE
(BUG) The app gets crashes when I click about & OSS licenses 

### ISSUE THREAD

**Issue by friendsmobile** [fennifith/Alarmio#47]
# Project Information

* Repository: https://github.com/fennifith/Alarmio
* Project Name: Alarmio
* My Github Account: https://github.com/friendsmobile
Download the application : [Here](https://play.google.com/store/apps/details?id=me.jfenn.alarmio)

# Expected behavior

When I click on About & OSS Licenses, the application should not be crashed when I click on  About & OSS Licenses should show details of the application 

# Actual behavior

 The app gets crashes when I click about & OSS licenses 

# How to reproduce

* open the application
* Go to the setting
* click on about & OSS licenses 
* Note the BUG

* Browser/App version: 1.0.1
* Operating system: 6.0

# Recording Of The Bug

![20190608_163718](https://user-images.githubusercontent.com/51118734/59146792-68a99a00-89a7-11e9-87f5-82f2463bc66b.gif)

# Logcat

<pre><code>D/AndroidRuntime(32068): Shutting down VM

E/AndroidRuntime(32068): FATAL EXCEPTION: main

E/AndroidRuntime(32068): Process: me.jfenn.alarmio, PID: 32068

E/AndroidRuntime(32068): android.content.res.Resources$NotFoundException: File res/drawable/ic_attribouter_github.xml from drawable resource ID #0x7f080079

E/AndroidRuntime(32068): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2946)

E/AndroidRuntime(32068): 	at android.content.res.Resources.loadDrawable(Resources.java:2821)

E/AndroidRuntime(32068): 	at android.content.res.Resources.getDrawable(Resources.java:1050)

E/AndroidRuntime(32068): 	at android.content.res.Resources.getDrawable(Resources.java:1032)

E/AndroidRuntime(32068): 	at android.content.Context.getDrawable(Context.java:403)

E/AndroidRuntime(32068): 	at androidx.core.a.a.a(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.appcompat.widget.i.a(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.appcompat.widget.i.a(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.appcompat.a.a.a.b(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.appcompat.widget.m.a(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.appcompat.widget.n.setImageResource(Unknown Source)

E/AndroidRuntime(32068): 	at me.jfenn.attribouter.f.c.a(Unknown Source)

E/AndroidRuntime(32068): 	at me.jfenn.attribouter.wedges.link.LinkWedge.a(Unknown Source)

E/AndroidRuntime(32068): 	at me.jfenn.attribouter.wedges.link.LinkWedge.a(Unknown Source)

E/AndroidRuntime(32068): 	at me.jfenn.attribouter.wedges.link.LinkWedge.a(Unknown Source)

E/AndroidRuntime(32068): 	at me.jfenn.attribouter.a.a.a(Unknown Source)

E/AndroidRuntime(32068): 	at me.jfenn.attribouter.a.a.a(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.recyclerview.widget.RecyclerView$a.a(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.recyclerview.widget.RecyclerView$a.b(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.recyclerview.widget.RecyclerView$p.a(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.recyclerview.widget.RecyclerView$p.a(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.recyclerview.widget.RecyclerView$p.a(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.recyclerview.widget.RecyclerView$p.c(Unknown Source)

E/AndroidRuntime(32068): 	at com.google.android.flexbox.FlexboxLayoutManager.o(Unknown Source)

E/AndroidRuntime(32068): 	at com.google.android.flexbox.FlexboxLayoutManager.a(Unknown Source)

E/AndroidRuntime(32068): 	at com.google.android.flexbox.d.a(Unknown Source)

E/AndroidRuntime(32068): 	at com.google.android.flexbox.d.a(Unknown Source)

E/AndroidRuntime(32068): 	at com.google.android.flexbox.FlexboxLayoutManager.q(Unknown Source)

E/AndroidRuntime(32068): 	at com.google.android.flexbox.FlexboxLayoutManager.c(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.recyclerview.widget.RecyclerView.N(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.recyclerview.widget.RecyclerView.onMeasure(Unknown Source)

E/AndroidRuntime(32068): 	at android.view.View.measure(View.java:17951)

E/AndroidRuntime(32068): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5797)

E/AndroidRuntime(32068): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)

E/AndroidRuntime(32068): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)

E/AndroidRuntime(32068): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)

E/AndroidRuntime(32068): 	at android.view.View.measure(View.java:17951)

E/AndroidRuntime(32068): 	at androidx.recyclerview.widget.RecyclerView$i.a_(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.recyclerview.widget.LinearLayoutManager.a(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.recyclerview.widget.LinearLayoutManager.a(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.recyclerview.widget.LinearLayoutManager.c(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.recyclerview.widget.RecyclerView.N(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.recyclerview.widget.RecyclerView.q(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source)

E/AndroidRuntime(32068): 	at android.view.View.layout(View.java:16075)

E/AndroidRuntime(32068): 	at android.view.ViewGroup.layout(ViewGroup.java:5300)

E/AndroidRuntime(32068): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)

E/AndroidRuntime(32068): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)

E/AndroidRuntime(32068): 	at android.view.View.layout(View.java:16075)

E/AndroidRuntime(32068): 	at android.view.ViewGroup.layout(ViewGroup.java:5300)

E/AndroidRuntime(32068): 	at com.google.android.material.appbar.c.b(Unknown Source)

E/AndroidRuntime(32068): 	at com.google.android.material.appbar.d.a(Unknown Source)

E/AndroidRuntime(32068): 	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.a(Unknown Source)

E/AndroidRuntime(32068): 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(Unknown Source)

E/AndroidRuntime(32068): 	at android.view.View.layout(View.java:16075)

E/AndroidRuntime(32068): 	at android.view.ViewGroup.layout(ViewGroup.java:5300)

E/AndroidRuntime(32068): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)

E/AndroidRuntime(32068): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)

E/AndroidRuntime(32068): 	at android.view.View.layout(View.java:16075)

E/AndroidRuntime(32068): 	at android.view.ViewGroup.layout(ViewGroup.java:5300)

E/AndroidRuntime(32068): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)

E/AndroidRuntime(32068): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)

E/AndroidRuntime(32068): 	at android.widget.Li
</code></pre>

**Comment by fennifith** [comment]
This is fixed in [`1.0.2`](https://github.com/fennifith/Alarmio/releases/tag/1.0.2), but not yet published due to CI errors.

**Comment by finn-cz** [comment]
Version 1.0.2 obtained from F-Droid repository keeps crashing too (Android 5.1, if it helps).

**Comment by fennifith** [comment]
Somehow I've deployed `1.0.3` and this is still not fixed...? It definitely has a valid token now. Not sure what horrible mishap has occurred, but this apparently needs some further investigation.

Related: fennifith/Attribouter#65

**Comment by fennifith** [comment]
(it _did_ work perfectly fine during testing, so it's definitely an auth-related problem, I'm just not sure what that problem is)

**Comment by fennifith** [comment]
I was wrong - it was a proguard/minification problem all along! fennifith/Attribouter#66 should add docs on this to prevent it from happening again.

Looking at the stack trace again, it should've been more obvious. It seems while I may have read the message "Resources$NotFoundException: File res/drawable/ic_attribouter_github.xml", I failed to understand what it meant. Don't know why I immediately jumped to it being auth issue.
