### ISSUE TITLE
Snooze

### ISSUE THREAD

**Issue by ikanakova** [fennifith/Alarmio#61]
## Device Info

- Brand: `Nokia`
- Model name: `Nokia 6.1`
- Android version: `Android 9`

## Steps to Reproduce

- Add new alarm
- Snooze alarm

## Expected behaviour
Silence for 2 minutes until repeat alarm.

## Actual behaviour
The alarm clock (timer) is still ringing: [video](https://devtube.dev-wiki.de/videos/watch/0024fc97-d9bf-45eb-a0e8-51ab11aa8a02)
Note: This ringing is different than adjusted alarm sound - it is system notification sound.

**Comment by fennifith** [comment]
Wow, I've never seen that happen before. Looks like something's gone horribly wrong with the recurring task inside [AlarmActivity](https://github.com/fennifith/Alarmio/blob/master/app/src/main/java/me/jfenn/alarmio/activities/AlarmActivity.java) after it's dismissed. Weird behavior.

**Comment by ikanakova** [comment]
I have tried reinstall app and problem still exist.

**Comment by quipri** [comment]
Does the behavior change based on whether or not repeat is enabled?

**Comment by ikanakova** [comment]
@quipri  The behavior does not change based on whether or not repeat is enabled. The first time I noticed it was repeat enabled, on the video above is repeat disabled.

**Comment by quipri** [comment]
I finally tried using snooze today, and I also experience this on a pixel 3. I'll try to look into it when I have time.

**Comment by quipri** [comment]
@fennifith I imagine you are one of those people who keeps notification sounds turned off. The problem seems to be that timers were repeatedly creating non-silent notifications.
