### ISSUE TITLE
Sync Alarms Across Devices

### ISSUE THREAD

**Issue by fennifith** [fennifith/Alarmio#7]
Idk how this would work. Firebase? Either way, having alarms, timers, etc. ring on multiple devices at once would be useful. I guess there could be sync options in the settings to choose what other devices should do (ex: this device has its own set of alarms but still syncs timers, or something).

**Comment by fennifith** [comment]
I'm wondering if it would be possible to implement this with WebRTC similar to what [chr15m/bugout](https://github.com/chr15m/bugout) does (although maybe not in JavaScript/Node). This would require at least one instance of the app to stay running in the background in order to connect to another device (maybe I could have one act as a persistent "server" for the others, displaying a persistent notification while active to prevent it from being killed a la #37 ), but should be usable, and would prevent a need to depend on something like Firebase as a backend (which would be an [AntiFeature](https://f-droid.org/wiki/page/Antifeature:NonFreeNet) in f-droid).

**Comment by kentone** [comment]
Maybe local settings backup and sync via external services? Nextcloud integration?
Maybe share the backup file and make it importable just tapping it? (Like sharing it on telegram)

**Comment by fennifith** [comment]
This will probably digress into its own fork / extension if I choose to work on it. #115 sufficiently covers this functionality for now.

If Alarmio does eventually integrate with a server-side component, it will be both open source and self-hostable - similar to how [ajayyy/AlarmioRemote](https://github.com/ajayyy/AlarmioRemote/) allows users to choose a server/domain. That's a long way off, though - and I don't want to complicate the codebase by adding too much functionality to it. A simple settings/data export should be fine for now.

Closing as obsolete.
