### ISSUE TITLE
Posibility of adding a song as ringtone

### ISSUE THREAD

**Issue by MarionMoseby** [fennifith/Alarmio#80]
I think itd be interesting

**Comment by quipri** [comment]
This has already been worked on, though it isn't in a release yet. Duplicate of #10

**Comment by MarionMoseby** [comment]
Sorry I failed to see it was a duplicate

**Comment by quipri** [comment]
No problem! If you have the ability to compile your own version of the develop branch, that feature is already available.

**Comment by fennifith** [comment]
I've been meaning to create a new release for a while, sorry. I was going to wait until the [`refactor`](https://github.com/fennifith/Alarmio/compare/refactor) branch was production-ready, but it seems like that won't be happening anytime soon given my lack of free time for the past few weeks, so the next release can proceed without it.

**Comment by MarionMoseby** [comment]
Ok, cool!
