### ISSUE TITLE
Radio alarm does not play over bluetooth

### ISSUE THREAD

**Issue by raboof** [fennifith/Alarmio#90]
When I'm connected to a bluetooth speaker for 'media audio' and a radio alarm goes off, I would like the radio to play on the bluetooth speaker, but right now it seems to play on the phone speaker.

**Comment by raboof** [comment]
Hmm, if I pair with bluetooth before the alarm goes off, it plays over both the phone speakers and bluetooth... (might be an upstream exoplayer issue of course)

**Comment by fennifith** [comment]
Thanks for the suggestion! I'm going to merge this with #32 for a general "audio options / volume panel" as a part of the ringtone picker interface; I'm assuming that a specific "bluetooth support" is not needed, as it should just pass through the media stream...
