### ISSUE TITLE
AlarmActivity in recent apps can be launched

### ISSUE THREAD

**Issue by neekless** [fennifith/Alarmio#96]
## Steps to Reproduce

- Set an alarm
- Swipe away Alarmio from recent apps
- Wait till alarm triggers
- Dismiss the alarm
- Go to recent apps and launch the AlarmActivity
- Alarm rings again

Users who dismissed their alarm can cause the alarm to ring again if they accidentally launch the AlarmActivity from recent apps long after the alarm was supposed to trigger.

## Solution
 Add `android:excludeFromRecents="true"` to `me.jfenn.alarmio.activities.AlarmActivity` in `AndroidManifest.xml`

Video of what I mean (no audio in this video but it does ring in real life): https://drive.google.com/open?id=11mPhdivZFsaRylrYeRdrjijL6yewFD-s

I have modified `AndroidManifest.xml` locally to include the solution and indeed AlarmActivity won't show in recents anymore. This is also the behavior of AOSP Clock.

**Comment by fennifith** [comment]
Thank you for the detailed issue report! I'll have that fixed in the next version :)
