### ISSUE TITLE
sound plays only from internal speaker but not via jack

### ISSUE THREAD

**Issue by b3nks** [fennifith/Alarmio#97]
I hoped waking up with alarmio and my soundsystem attached via jack would work, but the sound is only played via internal speakers of the phone.

**Comment by fennifith** [comment]
I'm pretty sure the sound needs to be playing over the device's media stream to go through the audio jack - Alarmio currently only uses the alarm stream, which will always use the phone's internal speaker. Options to change the audio "channel" should be implemented as a part of #32.
