### ISSUE TITLE
Add: reduce volume (alarm)

### ISSUE THREAD

**Issue by ghost** [fennifith/Alarmio#99]
Alarmio (1.0.4)
https://github.com/fennifith/Alarmio/releases/tag/1.0.4

## Device Info

- Brand: `Samsung`
- Model name: `Galaxy Note 10+`
- Android version: `10`

## Description

Hello when I use the Alarmio or the stock clock app on my Samsung Galaxy Note 10+.

Is there a function that was forgotten.

Reduce the volume for the ringtones a lot (make it quieter). On the Note 10+ stock clock app the volume can be made quieter, but the reduction is not enough.

It is still too loud for me.

Of all the volume controls I find the best of all, the video player apps like VLC for Android or MXPlayer.

Or the Android system itself for music playback etc..

I would like something like that for Alarmio. Can you support it?

**Comment by ajayyy** [comment]
This is now possible with the new implementation of alarm volume.

**Comment by fennifith** [comment]
Yep, this should be possible. I'm going to merge this with #32 - once proper volume controls exist in the ringtone picker, you'll be able to set it properly.

**Comment by ajayyy** [comment]
https://github.com/fennifith/Alarmio/pull/116
